# Hacemos visible la consola de H2
spring.h2.console.enabled=true
# Esta es la URL de la base de datos en memoria que Spring creó
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# Le decimos a Hibernate que "hable" en el dialecto de H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# show-sql y format-sql pueden generar logs muy verbosos, así que los dejo comentados
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true