# Hacemos visible la consola de H2
spring.h2.console.enabled=true
# Import environment variables from .env file
spring.config.import=optional:file:../../../.env[.properties]
# Esta es la URL de la base de datos en memoria que Spring creó
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
##################################################################33
# Le decimos a Hibernate que "hable" en el dialecto de H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# show-sql y format-sql pueden generar logs muy verbosos, así que los dejo comentados
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
######################################################################3
# Configuración de MongoDB local (desde docker-compose) - deshabilitada porque estamos proporcionando nuestro propio MongoClient bean
spring.mongodb.host=${MONGO_HOST}
spring.mongodb.port=${MONGO_PORT}
spring.mongodb.database=${MONGO_DATABASE}
spring.mongodb.username=${MONGO_USERNAME}
spring.mongodb.password=${MONGO_PASSWORD}
spring.mongodb.authentication-database=${MONGO_AUTH_DB}
# Configuración de MongoDB Atlas (comentada para desarrollo local)
